version: '3.8'

services:
  faultiz-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_CLOUD_API_KEY=${GOOGLE_CLOUD_API_KEY}
      - HUGGING_FACE_MODEL=${HUGGING_FACE_MODEL}
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS}
    volumes:
      - .:/app
    restart: always
